# gcp_info variables
PROJECT_ID = "hive-413217"
REGION = "us-central1",
BUCKET_NAME = "mock-retail-data"
BUCKET_OBJECT = "generated_data"
DATASET = "retail"
PRODUCT_TABLE = "product"
STORE_TABLE = "store"

# pubsublite parameters
project_number = "hive-413217"
cloud_region = "us-central1"
zone_id = "c"
reservation_id = "reservation"
throughput_capacity = 4
num_partitions = 2
regional = True
txn_topic_id = "transaction"
inv_topic_id = "inventory"
