version: 2

sources:
  - name: staging
    database: hive-413217
     # For postgres:
      #database: production
    schema: retail_2

    tables:
      - name: transactions
      - name: product_2
      - name: store_2

models:
    - name: transactions
    - name: product
    - name: store