# gcp_info variables
PROJECT_ID = "hive-413217"
REGION = "us-central1"
LOCATION = "US"
BUCKET_NAME = "mock-retail-data-2"
DATASET = "retail_2"
DBT_DATASET = "dbt_retail"
PRODUCT_TABLE = "product"
STORE_TABLE = "store"
